# Generated by Django 4.1.3 on 2024-05-27 15:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'InformUsers',
            },
        ),
    ]
