# Generated by Django 4.1.3 on 2024-06-23 12:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USMAApp', '0002_informusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllArchitects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArchitectName', models.CharField(max_length=1000)),
                ('ArchitectImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Github', models.CharField(blank=True, max_length=1000, null=True)),
                ('Youtube', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.CharField(blank=True, max_length=500, null=True)),
                ('Whatsapp', models.CharField(blank=True, max_length=1000, null=True)),
                ('Phone', models.CharField(blank=True, max_length=13, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'All Architects',
            },
        ),
        migrations.CreateModel(
            name='ArchitectureCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=1000)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ArchitectureCategories',
            },
        ),
        migrations.CreateModel(
            name='ArchitectureWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10000)),
                ('Year', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('MainImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('FrontViewImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('BackViewImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('LeftSideViewImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('RightSideViewImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('TopViewImage', models.ImageField(blank=True, null=True, upload_to='media/ArchitectureImage/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/ArchitecturePDF/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('ArchitectName', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.allarchitects')),
                ('CategoryName', models.ForeignKey(max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='USMAApp.architecturecategories')),
            ],
            options={
                'verbose_name_plural': 'ArchitectureWorks',
            },
        ),
    ]
